// author:- lokesh20018
// start defining the clock function...
function clock() {
  var pi = Math.PI; // value given out is in radians..
  var now = new Date(); // a new object calle date is been created (stae the use of the term "new" in the code..)
  var tools = document.getElementById('canvas').getContext('2d');  // captuer the element using selector , and get tools using Context...
  tools.save(); // save the default state... (in simple language  it saves the current state so that we can retrive it whenever we want...)
  tools.clearRect(0, 0, 400, 400); // clear the area for a new pattern to be drawn...
  tools.translate(200, 200); // move the origin of the canvas to 200px , 200px on the screen...
  // hour marks...
  tools.lineWidth = 6 ; // give a width to the hour marks...
  for (var i = 0; i < 12; i++) {
    tools.beginPath();    // the flow chart is to be disscussed in short (howto draw any shape in canvas)...
    tools.rotate(pi / 6); // rotating the canvas by 30 degrees to draw an hour mark ...
    tools.moveTo(100, 0); // starting point of the dash to be drawn...
    tools.lineTo(120, 0); // ending point of the dash line...
    tools.stroke();       // compeleting the stroke...
  }
  // extrating the time from object now...
  var sec = now.getSeconds(); // talking about the method...
  var min = now.getMinutes(); // talking about the method...
  var hr  = now.getHours(); //talking about the method...
  hr = ( hr >= 12 ? hr - 12 : hr ); // logic to convert the  24 hrour clock to 12 hour clock ..
  // drawing the hands of the clock....
  tools.rotate(-pi) ; //  rotating the canvas again by 180 degree to get the 12 O' clock at the top...
  var rh = hr * (pi / 6) + (pi / 360) * min + (pi / 21600) *sec ;// show the calculation of degrees ..
  drawHand(tools , rh , 80 , 14) ;  // drawing the respective hand byproviding the parameters....
  var rm = (pi / 30) * min + (pi / 1800) * sec ; // show the calculation in degrees ...
  drawHand(tools , rm , 85 , 8) ; // drawing the respective hand byproviding the parameters....
  var rs = sec * pi / 30 ; // show the calculation in degrees ...
  drawHand(tools , rs , 112 , 3) ; // drawing the respective hand byproviding the parameters....
  // function to draw hands....
  function drawHand(tools,r, length, width) {
    tools.save() ; // to save the sate so that we could restore the state once we want...
    tools.beginPath(); 
    tools.lineWidth = width;
    tools.moveTo(0,0);
    tools.rotate(r);
    tools.lineTo(0, length);
    tools.stroke();
    tools.restore() ; // to restore the state , so that we could get the initial canvas attributes back to draw another hand...
}
// giving a red boundry just to improve the look....
  tools.beginPath();
  tools.lineWidth = 14;
  tools.strokeStyle = 'red';
  tools.arc(0, 0, 142, 0, pi * 2);
  tools.stroke();

  tools.restore();// important ... we have to restore the first stored state stored state....
  // we used the save and restore functionality to set the state to base from where we had started...
  setInterval(clock , 1000) ; // this is an important step to anmiate the clock... by recursion or in simple language looping...
}
//call the function and start the clock...
clock() ;